export default {
  TOGGLE_THEME: "TOGGLE_THEME",

  FETCH_PROFILE_REQUEST: "FETCH_PROFILE_REQUEST",
  FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
  FETCH_PROFILE_ERROR: "FETCH_PROFILE_ERROR",
  LOGOUT: "LOGOUT"
};
