export default {
  TOGGLE_THEME: "TOGGLE_THEME",

  FETCH_FRIENDS_SUCCESS: "FETCH_FRIENDS_SUCCESS",

  FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_ERROR: "FETCH_USER_ERROR",
  
  LOGOUT: "LOGOUT"
};
